### ISSUE TITLE
Create catalog page

### ISSUE THREAD

**Issue by maciejors** [andrzejczukm/ChatRoom#19]
Add a catalog page. Requires #13 and #15 to be finished.

Subtasks:
- Create a file `src/routes/catalog/+page.svelte`. Implement the front-end there to the catalog list there
- Create a file `src/routes/catalog/[chatId]/+page.svelte`. Implement the front-end there to the catalog view there (see below for details).
- Create a file `src/database/catalog.js`. Add a function to it which will accept `chatId` and return a list of images data in this chat room. These attributes will probably be useful: file name, download url, maybe file size (whatever you think could be useful to display on this page).

**Comment by andrzejczukm** [comment]
Here's how I see it:

Each chat has its own catalog.

Upon entering a specific catalog, all the photos sent to that chat are displayed.

The user has the ability to:
- Select all photos
- Select specific photos
- Download the selected photos
- Choose whether the downloaded photos have their original titles or titles generated by the BLIP model.

**Comment by andrzejczukm** [comment]
EXAMPLE:
![example](https://github.com/andrzejczukm/ChatRoom/assets/72359059/91186988-1398-48b1-b774-865b0ce0e915)
