### ISSUE TITLE
Design security rules for Cloud Storage

### ISSUE THREAD

**Issue by maciejors** [andrzejczukm/ChatRoom#22]
### Rules to implement:
- Only chat members should have read and write access to chat's files

### Where to find rules editor?
Go to firebase console for this project. On the left-hand side: "Build" -> "Storage", then "Rules" at the top.

### How to design rules
A really good guide: https://firebase.google.com/docs/storage/security

**Comment by bieleckipiotr** [comment]
> * Only chat members should have read and write access to chat's files

this rule has been implemented, only chat members have read / create access, nobody has update/delete access.
Should we close this issue now?

**Comment by maciejors** [comment]
yep we can close this now
